'use strict';

module.exports = {
    Exception: require('./Exception'),
    InvalidArgumentException: require('./InvalidArgumentException'),
    NotFoundException: require('./NotFoundException'),
    NotFoundHTTPException: require('./NotFoundHTTPException'),
    MisconfigurationException: require('./MisconfigurationException'),
    NotCallableException: require('./NotCallableException'),
    DriverNotConnectedException: require('./DriverNotConnectedException'),
    DriverNotDefinedException: require('./DriverNotDefinedException'),
    RuntimeException: require('./RuntimeException'),
    UnresolvedDependencyException: require('./UnresolvedDependencyException'),
    BadMethodCallException: require('./BadMethodCallException'),
    UnsupportedMethodException: require('./UnsupportedMethodException'),
    DuplicateEntryException: require('./DuplicateEntryException'),
    SerializationException: require('./SerializationException'),
    ParseException: require('./ParseException'),
    AuthenticationException: require('./AuthenticationException'),
    ForbiddenHTTPException: require('./ForbiddenHTTPException'),
    RequestRejectedException: require('./RequestRejectedException'),
    HTTPException: require('./HTTPException'),
    InvalidHTTPRequestException: require('./InvalidHTTPRequestException'),
    MethodNotAllowedHTTPException: require('./MethodNotAllowedHTTPException'),
    UnauthorizedHTTPException: require('./UnauthorizedHTTPException'),
    AuthenticationRequiredHTTPException: require('./AuthenticationRequiredHTTPException'),
    AuthenticationHTTPException: require('./AuthenticationRequiredHTTPException'),
    UnsupportedAuthenticationMethodHTTPException: require('./UnsupportedAuthenticationMethodHTTPException'),
    InvalidCredentialsHTTPException: require('./InvalidCredentialsHTTPException'),
    TokenExpiredException: require('./TokenExpiredException'),
    UserNotFoundException: require('./UserNotFoundException'),
    MalformedAuthenticationAttemptHTTPException: require('./MalformedAuthenticationAttemptHTTPException')
};
